apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: local-sub-app-subscription
  namespace: default
  labels:
    app: local-sub-app
  annotations:
    apps.open-cluster-management.io/github-path: local-sub-op
    apps.open-cluster-management.io/github-branch: master
spec:
  channel: local-sub-ch/local-sub-channel
  placement:
    local: true
